force-app/main/default/objects/Managers_Assignment__c/Managers_Assignment__c.object-meta.xml
<CustomObject>
    <label>Managers Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Managers Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managers Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Managers_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Sub_Project__c</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <label>Sub Project</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/Project_Status__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Project Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Status__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Sub_Project__c</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sub_Project__c/Sub_Project__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sub Projects</relationshipLabel>
    <relationshipName>Sub_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectController.cls
public class ProjectController {
    
    @AuraEnabled
    public static List<ProjectWrapper> getProjectWithLastStatus() {
        List<ProjectWrapper> wrapper = resolveUserProjects();
        
        return wrapper;
    }
    
    public class ProjectWrapper {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String projectId { get; set; }
        @AuraEnabled public String project { get; set; }
        @AuraEnabled public String subProjectId { get; set; }
        @AuraEnabled public String subProject { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public DateTime lastdate { get; set; }
    }
    
    private static List<ProjectWrapper> resolveUserProjects() {
        List<Managers_Assignment__c> userAssignments = getUserAssignments();
        Map<Id, Set<Id>> userProjects = new Map<Id, Set<Id>>();
        
        for (Managers_Assignment__c assignment : userAssignments) {
            if (userProjects.get(assignment.Project__c) == null){
                Set<Id> aux = new Set<Id>();
                aux.add(assignment.Sub_Project__c);
                userProjects.put(assignment.Project__c, aux);
            }else{
                userProjects.get(assignment.Project__c).add(assignment.Sub_Project__c);
            }
            
        }
        
        Map<Id, List<Sub_Project__c>> userProjectsById = new Map<Id, List<Sub_Project__c>>(
            getProjectsById(userProjects)
        );
        
        List<Project_Status__c> projectStatus = getProjectStatusByProjectId(userProjects);
        Map<String, Project_Status__c> lastProjectStatusByProject = resolveLastProjectStatus(projectStatus);
        
        return resolveProjectWrapper(userProjectsById, lastProjectStatusByProject);
    }
    
    private static List<Managers_Assignment__c> getUserAssignments() {
        return [SELECT Id, Project__c, Sub_Project__c FROM Managers_Assignment__c WHERE User__c = :UserInfo.getUserId() AND Project__r.StageName NOT IN ('Closed/Won', 'Cancelled', 'Finished')];
    }
    
    private static List<Project_Status__c> getProjectStatusByProjectId(Map<Id, Set<Id>> projectIds) {
        return [
            SELECT
               Id,
               Project__c,
               Project__r.Name,
               Sub_Project__c,
               Sub_Project__r.Name, 
               Status__c,
               LastModifiedDate
            FROM Project_Status__c
            WHERE Project__c IN :projectIds.keyset()
            ORDER BY LastModifiedDate DESC
        ];
    }
    
    private static Map<String, Project_Status__c> resolveLastProjectStatus(List<Project_Status__c> projectStatus) {
        Map<String, Project_Status__c> lastProjectStatusByProject = new Map<String, Project_Status__c>();
        
        for (Project_Status__c pStatus : projectStatus) {
            String k = '';
            if (pStatus.Sub_Project__c != null){
                k = pStatus.Project__c + '-'+ pStatus.Sub_Project__c;
            }else{
                k = pStatus.Project__c; 
            }
            if (!lastProjectStatusByProject.containsKey(k)) {
                lastProjectStatusByProject.put(k, pStatus);
            }
        }
        
        return lastProjectStatusByProject;
    }
    
    private static Map<Id, List<Sub_Project__c>> getProjectsById(Map<Id, Set<Id>> projectIds) {
        Set<Id> oppIds = projectIds.keySet();
        List<Opportunity> opps = [SELECT Id, Name FROM Opportunity WHERE Id IN :oppIds];
        Map<Id, List<Sub_Project__c>> aux1 = new Map<Id, List<Sub_Project__c>>();
        for (Opportunity o: opps){
            aux1.put(o.Id, new List<Sub_Project__c>());
        }
            
        Set<Id> aux = new Set<Id>();
		for (Id i: projectIds.keySet()){
            aux.addAll(projectIds.get(i));
        }
        
        for (Sub_Project__c sp: [ SELECT id, Name, Project__c from Sub_Project__c where id in: aux]){
            if (aux1.containsKey(sp.Project__c)){
                aux1.get(sp.Project__c).add(sp);
            }else{
                List<Sub_Project__c> a = new List<Sub_Project__c>();
                a.add(sp);
                aux1.put(sp.Project__c, a);
            }
        }
        return aux1;
    }
    
    private static List<ProjectWrapper> resolveProjectWrapper(
        Map<Id, List<Sub_Project__c>> userProjectsById,
        Map<String, Project_Status__c> lastProjectStatusByProject
    ) {
        system.debug('=====lastProjectStatusByProject ='+ lastProjectStatusByProject);
        List<ProjectWrapper> wrapper = new List<ProjectWrapper>();
        Map<Id, String> lastStatusByProject = new Map<Id, String>();
        Map<id, Opportunity> opps = new Map<id, Opportunity>([SELECT Id, Name FROM Opportunity WHERE Id IN :userProjectsById.keySet()]);
        for (Id project : userProjectsById.keySet()) {
            
            if (userProjectsById.get(project).size()>0){
                // tiene subprojects
                for (Sub_Project__c subProject : userProjectsById.get(project)){
                    
                    String k = project + '-' + subProject.Id;
                    system.debug('===== k ='+ k);
                    if (lastProjectStatusByProject.containsKey(k)) {
                        ProjectWrapper newWrapper = getProjectWrapper(
                            lastProjectStatusByProject.get(k)
                        );
        
                        wrapper.add(newWrapper);
                    } else {
                        ProjectWrapper newWrapper = getProjectWrapper(opps.get(project), subProject);
                        wrapper.add(newWrapper);
                    }
                }
            }else{
                
                if (lastProjectStatusByProject.containsKey(project)) {
                    ProjectWrapper newWrapper = getProjectWrapper(
                        lastProjectStatusByProject.get(project)
                    );
    
                    wrapper.add(newWrapper);
            	} else {
                    ProjectWrapper newWrapper = getProjectWrapper(opps.get(project), null);
   
                    wrapper.add(newWrapper);
                }
        	}
            
        }
            

        return wrapper;
    }
    
    private static ProjectWrapper getProjectWrapper(Project_Status__c projectStatus) {
        ProjectWrapper newWrapper = new ProjectWrapper();
        newWrapper.id = projectStatus.Id;
        newWrapper.projectId = projectStatus.Project__c;
        newWrapper.project = projectStatus.Project__r.Name;
        newWrapper.subProjectId = projectStatus.Sub_Project__c;
        newWrapper.subProject = projectStatus.Sub_Project__r.Name;
        
        newWrapper.status = projectStatus.Status__c;
        newWrapper.lastdate = projectStatus.LastModifiedDate;
                    
        return newWrapper;
    }
    
    private static ProjectWrapper getProjectWrapper(Opportunity project, Sub_Project__c sp) {
        ProjectWrapper newWrapper = new ProjectWrapper();
        newWrapper.id = '';
        newWrapper.projectId = project.Id;
        newWrapper.project = project.Name;
        if (sp!= null){
            newWrapper.subProjectId = sp.Id;
        	newWrapper.subProject = sp.Name;
        }
        
        newWrapper.status = '';
                    
        return newWrapper;
    }
}