force-app/main/default/objects/Managers_Assignment__c/Managers_Assignment__c.object-meta.xml
<CustomObject>
    <label>Managers Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Managers Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managers Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Managers_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Sub_Project__c</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <label>Sub Project</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/Project_Status__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Project Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Status__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Sub_Project__c</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Statuses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sub_Project__c/Sub_Project__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sub Projects</relationshipLabel>
    <relationshipName>Sub_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectStatusController.cls
public class ProjectStatusController {

    @AuraEnabled
    public static List<ProjectStatusWrapper> getUserProjectStatus() {
        List<ProjectStatusWrapper> wrapper = new List<ProjectStatusWrapper>();
        
        List<Project_Status__c> userProjectStatus = resolveUserProjectStatus();
        for (Project_Status__c projectStatus : userProjectStatus) {
            ProjectStatusWrapper newWrapper = new ProjectStatusWrapper();
            newWrapper.project = projectStatus.Project__r.Name;
            newWrapper.subProject = projectStatus.Sub_Project__r.Name;
            newWrapper.status = projectStatus.Status__c;
            newWrapper.id = projectStatus.Id;
            wrapper.add(newWrapper);
        }
        
        return wrapper;
    }
    
    @AuraEnabled
    public static void createProjectStatus(String project, String subProject, String status, String comments, String meetingDate) {
        // #todo support sub project
        try {
            Project_Status__c projectStatus = new Project_Status__c(
                Project__c = project,
                Sub_Project__c = subProject,
                Status__c = status,
                Comments__c = comments
            );
            
            if (String.isNotBlank(meetingDate)) {
                projectStatus.Meeting_Date__c = Date.valueOf(meetingDate);
            }
            system.debug('======== '+ projectStatus);
            insert projectStatus;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static Map<String, String> getStatus() {
        Map<String, String> options = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Project_Status__c.Status__c.getDescribe();

        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry entry : pList) {
            options.put(entry.getValue(), entry.getLabel());
        }
        return options;
    }
    
    public class ProjectStatusWrapper {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String project { get; set; }
        @AuraEnabled public String subProject { get; set; }
        @AuraEnabled public String status { get; set; }
    }
    
    private static List<Project_Status__c> resolveUserProjectStatus() {
        List<Managers_Assignment__c> userAssignments = getUserAssignments();
        Set<Id> userProjects = new Set<Id>();
        
        for (Managers_Assignment__c assignment : userAssignments) {
            userProjects.add(assignment.Project__c);
        }
        
        return getProjectStatusByProjectId(userProjects);
    }
    
    private static List<Managers_Assignment__c> getUserAssignments() {
        return [SELECT Id, Project__c, Sub_Project__c FROM Managers_Assignment__c WHERE User__c = :UserInfo.getUserId()];
    }
    
    private static List<Project_Status__c> getProjectStatusByProjectId(Set<Id> projectIds) {
        return [SELECT Id, Project__c, Project__r.Name, Sub_Project__c, Sub_Project__r.Name, Status__c FROM Project_Status__c WHERE Project__c IN :projectIds];
    }
}