force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Base_Category__c.field-meta.xml
<CustomField>
    <fullName>Base_Category__c</fullName>
    <label>Base Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Sub_Project__c</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/Employee_Status__c.object-meta.xml
<CustomObject>
    <label>Employee Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Employee Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Status__c/fields/Certification_Comments__c.field-meta.xml
<CustomField>
    <fullName>Certification_Comments__c</fullName>
    <label>Certification Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Certification_Status__c.field-meta.xml
<CustomField>
    <fullName>Certification_Status__c</fullName>
    <inlineHelpText>Green = acorde al role o superior, Yellow = preparando, Red= no interesado</inlineHelpText>
    <label>Certification Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Statuses</relationshipLabel>
    <relationshipName>Employee_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Red_Reason__c.field-meta.xml
<CustomField>
    <fullName>Red_Reason__c</fullName>
    <inlineHelpText>Red Reasons: Salario, Role por el que cobra, Technology, otro</inlineHelpText>
    <label>Red Reason</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Estado a nivel de la empresa</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/Managers_Assignment__c.object-meta.xml
<CustomObject>
    <label>Managers Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Managers Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managers Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Managers_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Sub_Project__c</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sub_Project__c/Sub_Project__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sub Projects</relationshipLabel>
    <relationshipName>Sub_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeeStatusController.cls
public class EmployeeStatusController {

    @AuraEnabled
    public static List<EmployeeStatusWrapper> getUserEmployeeStatus() {
        List<EmployeeStatusWrapper> wrapper = new List<EmployeeStatusWrapper>();
        
        List<Employee_Status__c> userEmployeeStatus = resolveUserEmployeeStatus();
        for (Employee_Status__c employeeStatus : userEmployeeStatus) {
            EmployeeStatusWrapper newWrapper = new EmployeeStatusWrapper();
            newWrapper.employee = employeeStatus.Employee__r.Name;
            newWrapper.status = employeeStatus.Status__c;
            newWrapper.id = employeeStatus.Id;
            wrapper.add(newWrapper);
        }
        
        return wrapper;
    }
    
    @AuraEnabled
    public static void createEmployeeStatus(
        String employee,
        String status,
        String comments,
        String redReason,
        String certStatus,
        String certComments
    ) {
        try {
            Employee_Status__c employeeStatus = new Employee_Status__c(
                Employee__c = employee,
                Status__c = status,
                Comments__c = comments,
                Red_Reason__c = redReason,
                Certification_Status__c = certStatus,
                Certification_Comments__c = certComments
            );
                        
            insert employeeStatus;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
    
    @AuraEnabled
    public static Map<String, String> getStatus() {
        Map<String, String> options = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Employee_Status__c.Status__c.getDescribe();

        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry entry : pList) {
            options.put(entry.getValue(), entry.getLabel());
        }
        return options;
    }
    
    @AuraEnabled
    public static Map<String, String> getCertificationStatus() {
        Map<String, String> options = new Map<String, String>();
        Schema.DescribeFieldResult fieldResult = Employee_Status__c.Certification_Status__c.getDescribe();

        List<Schema.PicklistEntry> pList = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry entry : pList) {
            options.put(entry.getValue(), entry.getLabel());
        }
        return options;
    }
    
    public class EmployeeStatusWrapper {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String employee { get; set; }
        @AuraEnabled public String status { get; set; }
    }
    
    private static List<Employee_Status__c> resolveUserEmployeeStatus() {
        List<Managers_Assignment__c> userAssignments = getUserAssignments();
        Set<Id> userProjects = new Set<Id>();
        Map<String, Set<Id>> userSubProjects = new Map<String, Set<Id>>();
        
        for (Managers_Assignment__c assignment : userAssignments) {
            userProjects.add(assignment.Project__c);
            if (!String.isBlank(assignment.Sub_Project__c)){
                if (userSubProjects.get(assignment.Project__c) == null){
                    Set<Id> aux = new Set<Id>();
                    aux.add(assignment.Sub_Project__c);
                    userSubProjects.put(assignment.Project__c, aux);
                }else{
                    userSubProjects.get(assignment.Project__c).add(assignment.Sub_Project__c);
                }
                
            }
        }
        
        List<Employee_Assignment__c> employeeAssignments = getEmployeeAssignmentsByProjectId(userProjects, userSubProjects);
        
        Set<Id> employeeIds = new Set<Id>();
        for (Employee_Assignment__c employeeAssignment : employeeAssignments) {
            employeeIds.add(employeeAssignment.Employee__c);
        }

        return getEmployeeStatusByEmployeeIds(employeeIds);
    }
    
    private static List<Managers_Assignment__c> getUserAssignments() {
        return [SELECT Id, Project__c, Sub_Project__c FROM Managers_Assignment__c WHERE User__c = :UserInfo.getUserId()];
    }
    
    private static List<Employee_Assignment__c> getEmployeeAssignmentsByProjectId(Set<Id> projectIds, Map<String, Set<Id>> subProjects) {
        
        List<Employee_Assignment__c> toReturn = new List<Employee_Assignment__c>();
        for (Employee_Assignment__c ea: [SELECT Id, Employee__c, Project__c,  Sub_Project__c FROM Employee_Assignment__c WHERE Project__c IN :projectIds and Employee__r.Active__c = true and End_Date__c >: date.today() and Base_Category__c!='']){
            system.debug('======== Employee__c '+ ea.Employee__c);
            system.debug('======== Project__c '+ ea.Project__c);
            system.debug('======== Sub_Project__c '+ ea.Sub_Project__c);
            if (!String.isBlank(ea.Sub_Project__c) && subProjects.get(ea.Project__c)!= null && subProjects.get(ea.Project__c).contains(ea.Sub_Project__c)) {
                system.debug('======== added 1');
                toReturn.add(ea);
            }else{
                system.debug('======== added 2');
                toReturn.add(ea);
            }
        }
        return toReturn;
        
    }
    
    private static List<Employee_Status__c> getEmployeeStatusByEmployeeIds(Set<Id> employeeIds) {
        return [
            SELECT Id, Status__c, Employee__c, Employee__r.Name
            FROM Employee_Status__c
            WHERE Employee__r.Active__c= true and Employee__c IN :employeeIds
        ];
    }
}