force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/Employee_Status__c.object-meta.xml
<CustomObject>
    <label>Employee Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Employee Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Status__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Estado a nivel de la empresa</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/Managers_Assignment__c.object-meta.xml
<CustomObject>
    <label>Managers Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Managers Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managers Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Managers_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LWCEmployeeStatusControllerTest.cls
@isTest
public class LWCEmployeeStatusControllerTest {
    
    public static Employee_Assignment__c returnEmployeeProjectsStructure(Id eAssigmentId){
       //This method return the fields used by the getEmployeeProjects
         return [SELECT Project__r.Id, Project__r.Name FROM Employee_Assignment__c WHERE Id = :eAssigmentId];
    } 
    public static Employee_Status__c returnEmployeeStatusesStructure(Id currentId){
       //This method return the fields used by the getEmployeeStatuses
         return [SELECT Status__c, CreatedDate, Comments__c, CreatedBy.Name FROM Employee_Status__c WHERE Id = :currentId];
    } 
       
    @isTest
    public static void getEmployeeProjects(){
        //System Admin
    	User admin = TestDataFactory.createAdminUser();
        System.runAs(admin){
            //Account
            Account acc = TestDataFactory.createAccount();
            //Contact
            Contact con = TestDataFactory.createContact(acc.Id);
            //User
            User usr = TestDataFactory.createUser(con.Id);
            Id OppO1Id = TestDataFactory.createDataForTestProjectsTab('O1',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'),'BILLED');
            Id OppO2Id = TestDataFactory.createDataForTestProjectsTab('O2',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            Id OppO3Id = TestDataFactory.createDataForTestProjectsTab('O3',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            List<Employee_Assignment__c> empAssignmentList = new List<Employee_Assignment__c>();
           	empAssignmentList.add(returnEmployeeProjectsStructure(OppO1Id));
            empAssignmentList.add(returnEmployeeProjectsStructure(OppO2Id));
            empAssignmentList.add(returnEmployeeProjectsStructure(OppO3Id));
           	System.assertEquals(LWCEmployeeStatusController.getEmployeeProjects(con.Id).get(1).Project__r.Name, empAssignmentList.get(1).Project__r.Name,'One or more Projects do not match');
        }
    }
    
    @isTest
    public static void getEmployeeStatuses(){
    	 //System Admin
    	User admin = TestDataFactory.createAdminUser();
        System.runAs(admin){
            //Account
            Account acc = TestDataFactory.createAccount();
            //Contact
            Contact con = TestDataFactory.createContact(acc.Id);
            //User
            User usr = TestDataFactory.createUser(con.Id);
            Id OppO1Id = TestDataFactory.createDataForTestProjectsTab('O1',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            Id OppO2Id = TestDataFactory.createDataForTestProjectsTab('O2',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            Id OppO3Id = TestDataFactory.createDataForTestProjectsTab('O3',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            List<Employee_Assignment__c> empAssignmentList = new List<Employee_Assignment__c>();
           	empAssignmentList.add(returnEmployeeProjectsStructure(OppO1Id));
            empAssignmentList.add(returnEmployeeProjectsStructure(OppO2Id));
            empAssignmentList.add(returnEmployeeProjectsStructure(OppO3Id));
        	Employee_Status__c eS1 = TestDataFactory.createEmployeeStatus(con.Id,'Red', 'Red'); 
            update eS1;
            List<Employee_Status__c> status = new List<Employee_Status__c>();
            status.add(returnEmployeeStatusesStructure(eS1.Id));

            Test.startTest();
              System.assertEquals(LWCEmployeeStatusController.getEmployeeStatuses(con.Id, 0).get(0).Status__c, status.get(0).Status__c, 'One or more Statuses do not match');  
            Test.stopTest();
        }
    }
    
    @isTest
    public static void getEmployeeStatusCount(){
    	 //System Admin
    	User admin = TestDataFactory.createAdminUser();
        System.runAs(admin){
            //Account
            Account acc = TestDataFactory.createAccount();
            //Contact
            Contact con = TestDataFactory.createContact(acc.Id);
            //User
            User usr = TestDataFactory.createUser(con.Id);
            Id OppO1Id = TestDataFactory.createDataForTestProjectsTab('O1',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            Id OppO2Id = TestDataFactory.createDataForTestProjectsTab('O2',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            Id OppO3Id = TestDataFactory.createDataForTestProjectsTab('O3',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            List<Employee_Assignment__c> empAssignmentList = new List<Employee_Assignment__c>();
           	empAssignmentList.add(returnEmployeeProjectsStructure(OppO1Id));
            empAssignmentList.add(returnEmployeeProjectsStructure(OppO2Id));
            empAssignmentList.add(returnEmployeeProjectsStructure(OppO3Id));
        	Employee_Status__c eS1 = TestDataFactory.createEmployeeStatus(con.Id,'Red', 'Red');
            update eS1;
            List<Employee_Status__c> status = new List<Employee_Status__c>();
            status.add(returnEmployeeStatusesStructure(eS1.Id));

            Test.startTest();
              System.assertEquals(LWCEmployeeStatusController.getEmployeeStatusCount(con.Id), 1);         
                
            Test.stopTest();
        }
    }

    @isTest(SeeAllData=True)
    public static void sendMessage(){
        User admin = TestDataFactory.createAdminUser();
        Profile pAdmin = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User manager = TestDataFactory.createAdminManagerUser();
        System.runAs(admin){
            //Account
            Account acc = TestDataFactory.createAccount();
            //Contact
            Contact con = TestDataFactory.createContact(acc.Id);
            //User
            User usr = TestDataFactory.createUser(con.Id);
            
         	Id empAssignmentId = TestDataFactory.createDataForTestProjectsTab('O1',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            Id projectId = [SELECT Id, Name FROM Opportunity WHERE Name = 'O1' LIMIT 1].Id;
            Managers_Assignment__c mA1 = TestDataFactory.createManagersAssigment(manager.Id, projectId);
            Managers_Assignment__c mA2 = TestDataFactory.createManagersAssigment(manager.Id, projectId);
           
            List<Employee_Assignment__c> empAssignmentList = new List<Employee_Assignment__c>();
            Employee_Assignment__c eA1 = returnEmployeeProjectsStructure(empAssignmentId);
            eA1.Start_Date__c = date.parse('11/12/2020');
            eA1.End_Date__c = date.parse('11/12/2021');
            update eA1;
            empAssignmentList.add(eA1);
            
            Employee_Status__c eS1 = TestDataFactory.createEmployeeStatus(con.Id,'Red', 'Red');
            update eS1;

            List<String> lstManagersId = new List<String>();
            lstManagersId.add(manager.Id);
            List<Employee_Status__c> status = new List<Employee_Status__c>();
            status.add(returnEmployeeStatusesStructure(eS1.Id));
 		
            Test.startTest();
     		System.assertEquals(LWCEmployeeStatusController.sendMessage(lstManagersId, 'Test Test'), true, 'Message error');  
            Test.stopTest();
            }
        }
   
    @isTest
    public static void statusTabTests(){
        User admin = TestDataFactory.createAdminUser();
        Profile pAdmin = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User manager = TestDataFactory.createAdminManagerUser();
        System.runAs(admin){
            //Account
            Account acc = TestDataFactory.createAccount();
            //Contact
            Contact con = TestDataFactory.createContact(acc.Id);
            //User
            User usr = TestDataFactory.createUser(con.Id);
            
         	Id empAssignmentId = TestDataFactory.createDataForTestProjectsTab('O1',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), 'BILLED');
            Id projectId = [SELECT Id, Name FROM Opportunity WHERE Name = 'O1' LIMIT 1].Id;
            Managers_Assignment__c mA1 = TestDataFactory.createManagersAssigment(manager.Id, projectId);
            Managers_Assignment__c mA2 = TestDataFactory.createManagersAssigment(manager.Id, projectId);
           
            List<Employee_Assignment__c> empAssignmentList = new List<Employee_Assignment__c>();
            Employee_Assignment__c eA1 = returnEmployeeProjectsStructure(empAssignmentId);
            eA1.Start_Date__c = date.parse('11/12/2020');
            eA1.End_Date__c = date.parse('11/12/2021');
            update eA1;
            empAssignmentList.add(eA1);
            
            Employee_Status__c eS1 = TestDataFactory.createEmployeeStatus(con.Id,'Red', 'Red');
            update eS1;

            List<String> lstManagersId = new List<String>();
            lstManagersId.add(manager.Id);
            List<Employee_Status__c> status = new List<Employee_Status__c>();
            status.add(returnEmployeeStatusesStructure(eS1.Id));
 			            
            Test.startTest();
            System.assertEquals(LWCEmployeeStatusController.getManager(con.Id), lstManagersId, 'You dont have manager assigned');
            System.assertEquals(LWCEmployeeStatusController.getUser(con.Id), 'Test Test' , 'Contact do not match');
     		Test.stopTest();
            }
        }


}