force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/Managers_Assignment__c.object-meta.xml
<CustomObject>
    <label>Managers Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Managers Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managers Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Managers_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Billable.recordType-meta.xml
<RecordType>
    <fullName>Billable</fullName>
    <active>true</active>
    <businessProcess>Altimetrik</businessProcess>
    <label>Billable</label>
</RecordType>

force-app/main/default/objects/Project_Status__c/Project_Status__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Project Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Status__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/lookupfiledControllerTest.cls
@isTest
public class lookupfiledControllerTest {
    
    @isTest
    static void testAccountLookupField() {
        createTestData(false);
        List<string> returnFields = new List<string> {'Name'};
        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        lookupfieldController.objectDetails details;
        List<Account> accounts;
        List<Account> searchedAccounts;
        List<Account> singleAccount;
        Test.startTest();
        details = lookupfieldController.getObjectDetails('Account');
        accounts = (List<Account>) lookupfieldController.GetRecentRecords('Account', returnFields, 5);
        searchedAccounts = (List<Account>) lookupfieldController.SearchRecords(
            'Account', returnFields, returnFields, '', 'Name', 'ASC', 5, 'CreatedDate > 2001-01-01T00:00:01Z'
        );
        singleAccount = (List<Account>) lookupfieldController.GetRecord('Account', returnFields, acc.Id);
        Test.stopTest();
        
        System.assertEquals('Account', details.label);
        System.assertEquals(1, accounts.size(), 'All Accounts should have been retrieved');
        System.assertEquals(1, accounts.size(), 'All Accounts should have been retrieved');
        System.assertEquals(1, accounts.size(), 'An Account should have been retrieved');
    }
    
    @isTest
    static void testProjectLookupField() {
        createTestData(false);
        List<string> returnFields = new List<string> {'Name', 'CloseDate'};
        Opportunity project = [SELECT Id FROM Opportunity LIMIT 1];
        
        lookupfieldController.objectDetails details;
        List<Opportunity> projects;
        List<Opportunity> searchedProjects;
        List<Opportunity> singleProject;
        
        Test.startTest();
        details = lookupfieldController.getObjectDetails('Opportunity');
        projects = (List<Opportunity>) lookupfieldController.GetRecentRecords('Opportunity', returnFields, 5);
        searchedProjects = (List<Opportunity>) lookupfieldController.SearchRecords('Opportunity', returnFields, returnFields, '', 'Name', 'ASC', 5, 'CreatedDate > 2001-01-01T00:00:01Z');
        singleProject = (List<Opportunity>) lookupfieldController.GetRecord('Opportunity', returnFields, project.Id);
        Test.stopTest();
        
        System.assertEquals('Project', details.label);
        System.assertEquals(5, projects.size(), 'All Projects should have been retrieved');
        System.assertEquals(5, searchedProjects.size(), 'All Projects should have been retrieved');
        System.assertEquals(1, singleProject.size(), 'A Project should have been retrieved');
    }
    
    @isTest
    static void testEmployeeLookupField() {
        createTestData(false);
        List<string> returnFields = new List<string> {'Name'};
        Contact employee = [SELECT Id FROM Contact LIMIT 1];
        
        lookupfieldController.objectDetails details;
        List<Contact> employees;
        List<Contact> searchedEmployees;
        List<Contact> singleEmployee;
        
        Test.startTest();
        details = lookupfieldController.getObjectDetails('Contact');
        employees = (List<Contact>) lookupfieldController.GetRecentRecords('Contact', returnFields, 5);
        searchedEmployees = (List<Contact>) lookupfieldController.SearchRecords('Contact', returnFields, returnFields, '', 'Name', 'ASC', 5, 'CreatedDate > 2001-01-01T00:00:01Z');
        singleEmployee = (List<Contact>) lookupfieldController.GetRecord('Contact', returnFields, employee.Id);
        Test.stopTest();
        
        System.assertEquals('Employee', details.label);
        System.assertEquals(3, employees.size(), '3 Employees should have been retrieved');
        System.assertEquals(3, searchedEmployees.size(), '3 Employees should have been retrieved');
        System.assertEquals(1, singleEmployee.size(), 'An Employee should have been retrieved');
    }
    
    private static void createTestData(Boolean withProjectStatus) {
        Account acc = new Account(Name = '[TEST] Account');
        insert acc;
        
        List<Opportunity> projects = new List<Opportunity>();
        for (Integer i = 0; i < 5; i++) {
            projects.add(
                new Opportunity(
                    AccountId = acc.Id,
                    RecordTypeId = RecordTypeHelper.PROJECTS.BILLABLE,
                    Name = '[TEST] Opportunity ' + i,
                    StageName = Constants.PROJECTS.STAGE_PROSPECTING,
                    CloseDate = Date.today()
                )
            );
        }
        
        insert projects;
        
        List<Contact> employees = new List<Contact>();
        for (Integer i = 0; i < 5; i++) {
            employees.add(
                new Contact(
                    AccountId = acc.Id,
                    LastName = '[TEST] Employee ' + i,
                    Email = i + '@email.com'
                )
            );
        }
        insert employees;
        
        List<Employee_Assignment__c> employeeAssignments = new List<Employee_Assignment__c>();
        for (Integer i = 0; i < 3; i++) {
            employeeAssignments.add(
                new Employee_Assignment__c(
                    Project__c = projects.get(i).Id,
                    Employee__c = employees.get(i).Id
                )
            );
        }
        insert employeeAssignments;
        
        List<Managers_Assignment__c> assignments = new List<Managers_Assignment__c>();
        for (Opportunity project : projects) {
            assignments.add(
                new Managers_Assignment__c(
                    Project__c = project.Id,
                    User__c = UserInfo.getUserId()
                )
            );
        }
        
        insert assignments;
        
        if (withProjectStatus) {
            List<Project_Status__c> projectStatus = new List<Project_Status__c>();
            for (Opportunity project : projects) {
                projectStatus.add(
                    new Project_Status__c(
                        Project__c = project.Id,
                        Status__c = Constants.PROJECT_STATUS.STATUS_GREEN,
                        Comments__c = '[TEST] Comment',
                        Meeting_Date__c = Date.today()
                    )
                );
            }
            
            insert projectStatus;
        }
    }
}