force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/Employee_Status__c.object-meta.xml
<CustomObject>
    <label>Employee Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Employee Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Status__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Estado a nivel de la empresa</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review_Assignment__c/Review_Assignment__c.object-meta.xml
<CustomObject>
    <label>Review Assignment</label>
    <nameField>
        <label>Review Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Assignment__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Review Assignments</relationshipLabel>
    <relationshipName>Review_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review_Assignment__c/fields/Submitted_By_Evaluator__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By_Evaluator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted By Evaluator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LWCPerformanceEvaluationControllerTest.cls
@isTest
public class LWCPerformanceEvaluationControllerTest {
    
    public static Employee_Assignment__c returnEmployeeProjectsStructure(Id eAssigmentId){
       //This method return the fields used by the getEmployeeProjects
         return [SELECT Project__r.Id, Project__r.Name FROM Employee_Assignment__c WHERE Id = :eAssigmentId];
    } 
    public static Employee_Status__c returnEmployeeStatusesStructure(Id currentId){
       //This method return the fields used by the getEmployeeStatuses
         return [SELECT Status__c, CreatedDate, Comments__c, CreatedBy.Name FROM Employee_Status__c WHERE Id = :currentId];
    } 
    @isTest
public static void getEmployeeStatuses(){
     //System Admin
    User admin = TestDataFactory.createAdminUser();
    System.runAs(admin){
        //Account
        Account acc = TestDataFactory.createAccount();
        //Contact
        Contact con = TestDataFactory.createContact(acc.Id);
        //User
        User usr = TestDataFactory.createUser(con.Id);
        Id OppO1Id = TestDataFactory.createDataForTestProjectsTab('O1',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), '');
        Id OppO2Id = TestDataFactory.createDataForTestProjectsTab('O2',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), '');
        Id OppO3Id = TestDataFactory.createDataForTestProjectsTab('O3',acc.Id, con.Id, date.parse('11/12/2020'), date.parse('2/17/2021'), '');
        List<Employee_Assignment__c> empAssignmentList = new List<Employee_Assignment__c>();
           empAssignmentList.add(returnEmployeeProjectsStructure(OppO1Id));
        empAssignmentList.add(returnEmployeeProjectsStructure(OppO2Id));
        empAssignmentList.add(returnEmployeeProjectsStructure(OppO3Id));
        Employee_Status__c eS1 = TestDataFactory.createEmployeeStatus(con.Id,'Red', 'Red'); 
        update eS1;
        List<Employee_Status__c> status = new List<Employee_Status__c>();
        status.add(returnEmployeeStatusesStructure(eS1.Id));

        Test.startTest();
          System.assertEquals(LWCEmployeeStatusController.getEmployeeStatuses(con.Id, 0).get(0).Status__c, status.get(0).Status__c, 'One or more Statuses do not match');         
          LWCPerformanceEvaluationController.getEmployeeReview(con.Id, 'Reviews about me',null);         
          LWCPerformanceEvaluationController.getEmployeeReview(con.Id, 'Reviews done',null);         
          LWCPerformanceEvaluationController.getEmployeeReview(con.Id, 'Reviews to do',null);         
          LWCPerformanceEvaluationController.getEmployeeReviewCount(con.Id, 'Reviews to do');         
          LWCPerformanceEvaluationController.getEmployeeReviewCount(con.Id, 'Reviews done');         
          LWCPerformanceEvaluationController.getEmployeeReviewCount(con.Id, 'Reviews about me');         
        Test.stopTest();
    }
}

@isTest
public static void submittedByEvaluatorTest(){
  //System Admin
  User admin = TestDataFactory.createAdminUser();
  System.runAs(admin) {
      Account acc = TestDataFactory.createAccount();
      Contact con = TestDataFactory.createContact(acc.Id);
      Opportunity project = TestDataFactory.createOpportunity('Test', acc.Id);
      Review__c review = TestDataFactory.createReview(con.Id, project.Id, 'Open');
      Review_Assignment__c reviewAssignment = TestDataFactory.createReviewAssignment(review.Id, con.Id);
      
      Test.startTest();
      LWCPerformanceEvaluationController.updateSubmittedByEvaluator(reviewAssignment.Id);
      Test.stopTest();
      Review_Assignment__c reviewAssignmentUpdate = [ SELECT Submitted_By_Evaluator__c FROM Review_Assignment__c WHERE Id = :reviewAssignment.Id ];
      System.assertEquals(true, reviewAssignmentUpdate.Submitted_By_Evaluator__c);
  }
}


}