force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Base_Category__c.field-meta.xml
<CustomField>
    <fullName>Base_Category__c</fullName>
    <label>Base Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/Employee_Status__c.object-meta.xml
<CustomObject>
    <label>Employee Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Employee Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Status__c/fields/Certification_Status__c.field-meta.xml
<CustomField>
    <fullName>Certification_Status__c</fullName>
    <inlineHelpText>Green = acorde al role o superior, Yellow = preparando, Red= no interesado</inlineHelpText>
    <label>Certification Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Statuses</relationshipLabel>
    <relationshipName>Employee_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Estado a nivel de la empresa</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Evaluated_KPI__c/Evaluated_KPI__c.object-meta.xml
<CustomObject>
    <label>Evaluated KPI</label>
    <nameField>
        <label>Evaluated KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluated KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluated_KPI__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI</label>
    <referenceTo>KPI__c</referenceTo>
    <relationshipLabel>Evaluated KPIs</relationshipLabel>
    <relationshipName>Evaluated_KPIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evaluated_KPI__c/fields/Point__c.field-meta.xml
<CustomField>
    <fullName>Point__c</fullName>
    <label>Point</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluated_KPI__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Evaluated KPIs</relationshipLabel>
    <relationshipName>Evaluated_KPIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KPI__c/KPI__c.object-meta.xml
<CustomObject>
    <label>KPI</label>
    <nameField>
        <label>KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KPI__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>val1</fullName>
            </value>
            <value>
                <fullName>val2</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/Managers_Assignment__c.object-meta.xml
<CustomObject>
    <label>Managers Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Managers Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managers Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Managers_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan_Item__c/Plan_Item__c.object-meta.xml
<CustomObject>
    <label>Plan Item</label>
    <nameField>
        <label>Plan Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Item__c/fields/Plan__c.field-meta.xml
<CustomField> 
    <fullName>Plan__c</fullName> 
    <label>Plan</label> 
    <length>131072</length> 
    <type>LongTextArea</type> 
</CustomField>

force-app/main/default/objects/Plan_Item__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Plan Items</relationshipLabel>
    <relationshipName>Plan_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Item__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non Started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project_Status__c/Project_Status__c.object-meta.xml
<CustomObject>
    <label>Project Status</label>
    <nameField>
        <displayFormat>PS-{0000}</displayFormat>
        <label>Project Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Project Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Project_Status__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <label>Meeting Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Project Statuses</relationshipLabel>
    <relationshipName>Project_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Evaluated__c.field-meta.xml
<CustomField>
    <fullName>Evaluated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluated</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review_Assignment__c/Review_Assignment__c.object-meta.xml
<CustomObject>
    <label>Review Assignment</label>
    <nameField>
        <label>Review Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Assignment__c/fields/Evaluator__c.field-meta.xml
<CustomField>
    <fullName>Evaluator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Review Assignments</relationshipLabel>
    <relationshipName>Review_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review_Assignment__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Review Assignments</relationshipLabel>
    <relationshipName>Review_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {

    public static User createAdminUser(){
        Profile pAdmin = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        UserRole uRoleAdmin = [SELECT Id, Name FROM UserRole WHERE Name = 'CEO' LIMIT 1];
        User admin = new User();
        admin.firstname = 'Admin1';
        admin.lastname = 'Admin1';
        admin.Alias = 'aAdmin1';
        admin.email = 'aAdmin1@admin.com';
        admin.username = 'aAdmin1@admin.com';
        admin.UserRoleId = uRoleAdmin.Id;
        admin.profileId = pAdmin.id;
        admin.emailencodingkey ='UTF-8';
        admin.languagelocalekey ='en_US';
        admin.localesidkey ='en_US';
        admin.timezonesidkey ='America/Los_Angeles';
        insert admin;
        return admin;
    }
    
    public static User createAdminManagerUser(){
        Profile pAdmin = [SELECT Id, Name FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        User admin = new User();
        admin.firstname = 'Manager';
        admin.lastname = 'Manager';
        admin.Alias = 'Manager';
        admin.email = 'manager@admin.com';
        admin.username = 'project_manager@admin.com';
        admin.profileId = pAdmin.id;
        admin.emailencodingkey ='UTF-8';
        admin.languagelocalekey ='en_US';
        admin.localesidkey ='en_US';
        admin.timezonesidkey ='America/Los_Angeles';
        insert admin;
        return admin;
    }

    public static Contact createContact(Id accountId){
        Contact con = new Contact();
        con.FirstName='Test';
        con.LastName='Test';
        con.Email = 'Test@test.com';
        con.AccountId = accountId;
        insert con;
        return con;
    }

    public static Account createAccount(){
       Account acc = new Account();
       acc.Name = 'accountForTest';
       insert acc;
       return acc;
    }

    public static User createUser(Id contactId){
        String orgId = UserInfo.getOrganizationId();
        String dateString = String.valueof(Datetime.now()).replace(' ','').replace(':','').replace('-','');
        Integer randomInt = Integer.valueOf(math.rint(math.random()*1000000));
        String uniqueName = orgId + dateString + randomInt;
        User usr = new User();
        Profile pUser = [SELECT Id FROM Profile WHERE Name = 'Community Employee Profile' LIMIT 1];
        usr.firstname = 'Sebastian';
        usr.lastname = 'Trelles';
        usr.Alias = uniqueName.substring(18, 23);
        usr.email = uniqueName+'@test.com';
        usr.username = uniqueName+'@test.com';
        usr.profileId = pUser.id;
        usr.emailencodingkey ='UTF-8';
        usr.languagelocalekey ='en_US';
        usr.localesidkey ='en_US';
        usr.timezonesidkey ='America/Los_Angeles';
        usr.ContactId = contactId;
        insert usr;
        return usr;
    }

    public static ta_User_Info__c createUserInfo(string trailBlazerId){
        ta_User_Info__c userInfo = new ta_User_Info__c();
        userInfo.Name='Test';
        userInfo.Email__c = 'Test@test.com';
        userInfo.Role__c = 'Developer';
        userInfo.TrailBlazerId__c = trailBlazerId;
        insert userInfo;
        return userInfo;
    }

    public static Opportunity createOpportunity(String name, Id accountId){
        Opportunity opp = new Opportunity();
        opp.Name = name;
        opp.CloseDate = system.today();
        opp.StageName = 'Accepted';
        opp.AccountId = accountId;
        insert opp;
        return opp;
    }

    public static Employee_Assignment__c createEmployeeAssigment(Id contactId, Id opportunityId, Date startDate, Date endDate, String baseCat){
        Employee_Assignment__c eAssignment = new Employee_Assignment__c();
        eAssignment.Employee__c = contactId;
        eAssignment.Project__c = opportunityId;
        eAssignment.Start_Date__c = startDate;
        eAssignment.Base_Category__c = baseCat;
        eAssignment.End_Date__c = endDate;
        insert eAssignment;
        return eAssignment;
    }

    public static Project_Status__c createProjectStatus(Id opportunityId, String status){
        Project_Status__c pStatus = new Project_Status__c();
        pStatus.Project__c = opportunityId;
        pStatus.Comments__c = 'Test';
        pStatus.Meeting_Date__c = system.today();
        pStatus.Status__c = status;
        insert pStatus;
        return pStatus;
    }

    public static Id createDataForTestProjectStatusImageName(String name, Id accountId, Id conntactId, String status, Date startDate, Date endDate, String baseCat){
    	//Opportunity
        Opportunity opp = createOpportunity(name, accountId);
        //Employee Assignment
        Employee_Assignment__c eAssignment = createEmployeeAssigment(conntactId, opp.Id, startDate, endDate, baseCat);
        //If status is null do not create Project Status
        if(status != ''){
            //Project Status
            Project_Status__c pStatus = createProjectStatus(opp.Id, status); 
        }
       	return opp.Id;
    }

    public static Employee_Assignment__c createDataForBenchReport(String name, Id accountId, Id conntactId, Date startDate, Date endDate, String baseCat){
        //Opportunity
        Opportunity opp = createOpportunity(name, accountId);
        //Employee Assignment
        Employee_Assignment__c eAssignment = createEmployeeAssigment(conntactId, opp.Id, startDate, endDate, baseCat);
        //If status is null do not create Project Status
        return eAssignment;
    }

    public static Id createDataForTestProjectsTab(String name, Id accountId, Id conntactId, Date startDate, Date endDate, String baseCat){
    	//Opportunity
        Opportunity opp = createOpportunity(name, accountId);
        //Employee Assignment
        Employee_Assignment__c eAssignment = createEmployeeAssigment(conntactId, opp.Id, startDate, endDate, baseCat);
        return eAssignment.Id;
    }

    public static Employee_Status__c createEmployeeStatus(Id contactId, String status, String certificationStatus){
        Employee_Status__c eStatus = new Employee_Status__c();
        eStatus.Employee__c = contactId;
        eStatus.Status__c = status;
        eStatus.Certification_Status__c = certificationStatus;
        insert eStatus;
        return eStatus;
    }

    public static Managers_Assignment__c createManagersAssigment(Id managerId, Id opportunityId){
        Managers_Assignment__c mAssignment = new Managers_Assignment__c();
        mAssignment.Project__c = opportunityId;
        mAssignment.User__c = managerId;
        insert mAssignment;
        return mAssignment;
    }

    public static Review__c createReview(Id contactId, Id opportunityId, String status){
        Review__c review = new Review__c();
        review.Evaluated__c = contactId;
        review.Project__c = opportunityId;
        review.Status__c = status;
        insert review;
        return review;
    }

    public static Review_Assignment__c createReviewAssignment(Id reviewId, Id evaluatorId){
        Review_Assignment__c reviewAssignment = new Review_Assignment__c();
        reviewAssignment.Evaluator__c = evaluatorId;
        reviewAssignment.Review__c = reviewId;
        reviewAssignment.Name = 'Review Assignment Test';
        insert reviewAssignment;
        return reviewAssignment;
    }

    public static Plan_Item__c createPlanItem(Id reviewId, String status, Date endDate){
        Plan_Item__c planItem = new Plan_Item__c();
        planItem.Review__c = reviewId;
        planItem.State__c = status;
        planItem.Name = 'Test Plan Item';
        planItem.Plan__c = 'Test Plan Description';
        planItem.End_Date__c = endDate;
        insert planItem;
        return planItem;
    }

    public static Kpi__c createKpis(String name){
        Kpi__c kpi = new Kpi__c();
        kpi.Role__c = 'Developer';
        kpi.Name = name;
        insert kpi;
        return kpi;
    }
    public static Evaluated_Kpi__c createEvaluatedKpi(Id reviewId, Id kpiId, Integer Point){
        Evaluated_Kpi__c evaluatedKpi = new Evaluated_Kpi__c();
        evaluatedKpi.Review__c = reviewId;
        evaluatedKpi.Kpi__c = kpiId;
        evaluatedKpi.Name = 'Test Evaluated Kpi';
        evaluatedKpi.Point__c = 4;
        insert evaluatedKpi;
        return evaluatedKpi;
    }


}