force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Evaluated__c.field-meta.xml
<CustomField>
    <fullName>Evaluated__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluated</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Reviews</relationshipLabel>
    <relationshipName>Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review_Assignment__c/Review_Assignment__c.object-meta.xml
<CustomObject>
    <label>Review Assignment</label>
    <nameField>
        <label>Review Assignment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review_Assignment__c/fields/Evaluator__c.field-meta.xml
<CustomField>
    <fullName>Evaluator__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluator</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Review Assignments</relationshipLabel>
    <relationshipName>Review_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review_Assignment__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Review Assignments</relationshipLabel>
    <relationshipName>Review_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review_Assignment__c/fields/Submitted_By_Evaluator__c.field-meta.xml
<CustomField>
    <fullName>Submitted_By_Evaluator__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted By Evaluator</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/LWCPerformanceEvaluationController.cls
public without sharing class LWCPerformanceEvaluationController {

    public static List<SObject> getEmployeeReviewQueries(String empId,string filterStatus, Integer offsetRange){
        set<String> statusFilter = new set<String>();
        if (filterStatus == 'Reviews about me'){
            statusFilter.add('Approved');
            if(offsetRange == null){
                return [SELECT Id, Review__r.Status__c, Review__r.CreatedDate, Review__r.Comments__c, Review__r.CreatedBy.Name,Review__r.Evaluated__r.name, Review__c, Evaluator__r.name FROM Review_Assignment__c WHERE Review__r.Evaluated__c =: empId AND Review__r.Status__c IN : statusFilter ORDER BY CreatedDate DESC LIMIT 4];
            }else {
                return [SELECT Id, Review__r.Status__c, Review__r.CreatedDate, Review__r.Comments__c, Review__r.CreatedBy.Name,Review__r.Evaluated__r.name, Review__c, Evaluator__r.name FROM Review_Assignment__c WHERE Review__r.Evaluated__c =: empId AND Review__r.Status__c IN : statusFilter ORDER BY CreatedDate DESC LIMIT 4 OFFSET :offsetRange];

            }

        }
         else if (filterStatus == 'Reviews done') {
            statusFilter.add('Submitted');
            statusFilter.add('Approved');
            if(offsetRange == null){
                return [SELECT Id, Review__c, Review__r.Status__c, Review__r.CreatedDate, Review__r.Comments__c, Review__r.CreatedBy.Name,Review__r.Evaluated__r.name FROM Review_Assignment__c WHERE Evaluator__c =: empId AND (Review__r.Status__c IN : statusFilter OR Submitted_by_Evaluator__c = TRUE) ORDER BY CreatedDate DESC LIMIT 4];
            }else {
                return [SELECT Id, Review__c, Review__r.Status__c, Review__r.CreatedDate, Review__r.Comments__c, Review__r.CreatedBy.Name,Review__r.Evaluated__r.name FROM Review_Assignment__c WHERE Evaluator__c =: empId AND (Review__r.Status__c IN : statusFilter OR Submitted_by_Evaluator__c = TRUE) ORDER BY CreatedDate DESC LIMIT 4 OFFSET :offsetRange];
            }
            
        }else if (filterStatus == 'Reviews to do') {
            statusFilter.add('Open');
            statusFilter.add('In Progress');
            
            if(offsetRange == null){
                return [SELECT Id, Review__c,Review__r.Status__c, Review__r.CreatedDate, Review__r.Comments__c, Review__r.CreatedBy.Name,Review__r.Evaluated__r.name FROM Review_Assignment__c WHERE Evaluator__c =:empId AND Review__r.Status__c IN : statusFilter ORDER BY CreatedDate DESC LIMIT 4];
            }else {
                return [SELECT Id, Review__c,Review__r.Status__c, Review__r.CreatedDate, Review__r.Comments__c, Review__r.CreatedBy.Name,Review__r.Evaluated__r.name FROM Review_Assignment__c WHERE Evaluator__c =:empId AND Review__r.Status__c IN : statusFilter ORDER BY CreatedDate DESC LIMIT 4  OFFSET :offsetRange];
            }
        }else {
            return null;
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<SObject> getEmployeeReview(String empId,string filterStatus, Integer offsetRange){
       return  getEmployeeReviewQueries(empId, filterStatus, offsetRange);
    }

    @AuraEnabled(cacheable=false)
    public static List<SObject> getEmployeeReviewNonCacheable(String empId,string filterStatus, Integer offsetRange){
        return  getEmployeeReviewQueries(empId, filterStatus, offsetRange);
    }
   
    @AuraEnabled(cacheable=true)
    public static Integer getEmployeeReviewCount(String empId,string filterStatus){
        system.debug('empId '+empId);
        system.debug('count review'+[SELECT COUNT() FROM Review__c WHERE Evaluated__c = :empId]);
        set<String> statusFilter = new set<String>();
        
        if (filterStatus == 'Reviews about me'){
            statusFilter.add('Approved');
            return [SELECT COUNT() FROM Review__c WHERE Evaluated__c =:empId AND Status__c IN : statusFilter];

        }
         else if (filterStatus == 'Reviews done') {
            statusFilter.add('Submitted');
            statusFilter.add('Approved');

            return [SELECT COUNT() FROM Review_Assignment__c WHERE Evaluator__c =: empId AND Review__r.Status__c IN : statusFilter];
            
        }else if (filterStatus == 'Reviews to do') {
            statusFilter.add('Open');
            statusFilter.add('In Progress');
            
            return [SELECT COUNT() FROM Review_Assignment__c WHERE Evaluator__c =:empId AND Review__r.Status__c IN : statusFilter];
        }else {
            return null;
        }
    }

    @AuraEnabled(Cacheable=false)
    public static boolean updateSubmittedByEvaluator(String reviewAssignmentId){
        try{
            Review_assignment__c reviewAssignment = [Select Id, Submitted_By_Evaluator__c from Review_assignment__c WHERE Id =: reviewAssignmentId];
            reviewAssignment.Submitted_By_Evaluator__c = true;
            update reviewAssignment;
            return true;        
        } catch (Exception e) {
            return false;
        }
    }
}