force-app/main/default/objects/Community_Request_Notification__c/Community_Request_Notification__c.object-meta.xml
<CustomObject>
    <label>Community Request Notification</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Request Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Request_Notification__c/fields/Request_type__c.field-meta.xml
<CustomField>
    <fullName>Request_type__c</fullName>
    <label>Request_type</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/Employee_Status__c.object-meta.xml
<CustomObject>
    <label>Employee Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Employee Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Status__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Statuses</relationshipLabel>
    <relationshipName>Employee_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Estado a nivel de la empresa</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/Managers_Assignment__c.object-meta.xml
<CustomObject>
    <label>Managers Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Managers Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managers Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Managers_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LWCEmployeeStatusController.cls
public without sharing class LWCEmployeeStatusController {

    @AuraEnabled(cacheable=true)
    public static List<Employee_Assignment__c> getEmployeeProjects(String empId){
        List<Employee_Assignment__c> eAList = new List<Employee_Assignment__c>();
        //Get projects only once
        Id auxId;
        for (Employee_Assignment__c current_eA : [SELECT Project__r.Id, Project__r.Name FROM Employee_Assignment__c WHERE Employee__r.Id = :empId ORDER BY Project__r.Name]){
            if(eAList.isEmpty()){
                eAList.add(current_eA);
            }else{
                if (current_eA.Project__r.Id != auxId) {
                    eAList.add(current_eA);
                }
            }
            auxId = current_eA.Project__r.Id;
        }
        return eAList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Employee_Status__c> getEmployeeStatuses(String empId, Integer offsetRange){
        if(offsetRange == null){
            return [SELECT Id, Status__c, CreatedDate, Comments__c, CreatedBy.Name FROM Employee_Status__c WHERE Employee__r.Id =:empId ORDER BY CreatedDate DESC LIMIT 4];
        }else {
            return [SELECT Id, Status__c, CreatedDate, Comments__c, CreatedBy.Name FROM Employee_Status__c WHERE Employee__r.Id =:empId ORDER BY CreatedDate DESC LIMIT 4 OFFSET :offsetRange];
        }
    }

    @AuraEnabled(cacheable=true)
    public static Integer getEmployeeStatusCount(String empId){
        return [SELECT COUNT() FROM Employee_Status__c WHERE Employee__r.Id = :empId];
    }

      
   
   

    @AuraEnabled(cacheable=true)
    public static List<String> getManager(String empId){
        List<String> lstProjectsActive = new List<String>();
        for(Employee_Assignment__c activeProj : [SELECT Project__r.Id FROM Employee_Assignment__c WHERE Employee__r.Id = :empId AND Active__c = true]){
            lstProjectsActive.add(activeProj.Project__r.Id);
        }
        List<String> lstManagersId = new List<String>();
        if(!lstProjectsActive.isEmpty()){
            for(Managers_Assignment__c currentMA : [SELECT User__r.Id FROM Managers_Assignment__c WHERE Project__r.Id IN :lstProjectsActive ORDER BY Project__r.Id]){
                if(lstManagersId.isEmpty()) {
                    lstManagersId.add(currentMA.User__r.Id);
                }else{
                    if(!lstManagersId.contains(currentMA.User__r.Id)){
                        lstManagersId.add(currentMA.User__r.Id);
                    }
                }
           } 
           return lstManagersId;
        }
        lstManagersId.add('You dont have manager assigned');
        return lstManagersId;
    }

    @AuraEnabled(cacheable=true)
    public static string getUser(String empId){
        return [SELECT Contact.Name FROM User WHERE Contact.Id =: empId LIMIT 1].Contact.Name;
    }
 
    @AuraEnabled
    public static Boolean sendMessage(List<String> lstManagersId, String userName){
       return feedMessage(lstManagersId, userName);
    }

    public static Boolean feedMessage(List<String> lstManagersId, String userName){
        String requestType = 'Status';

        List<Community_Request_Notification__c> statusNotification = [
            SELECT LastModifiedDate, OwnerId FROM Community_Request_Notification__c WHERE CreatedById = :UserInfo.getUserId() AND Request_type__c = :requestType LIMIT 1
            ];
            DateTime last24hours = System.Now()-1;
        try {
            if(statusNotification.isEmpty() || statusNotification.get(0).LastModifiedDate < last24hours){
                String postText = 'The Employee '  + userName + ' requests a status update.';
                Community_Request_Notification__c newStatusNotification = new Community_Request_Notification__c();
                newStatusNotification.Request_type__c = requestType;
                if(statusNotification.isEmpty()){
                    insert newStatusNotification;
                }else{
                    upsert statusNotification;
                }      
                  
                // Define the FeedItemInput object to pass to postFeedElement
                ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
                ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
                ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
                ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
                textSegmentInput.text = postText;
                //The MessageBodyInput object holds the text in the post
                messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();
                messageBodyInput.messageSegments.add(textSegmentInput);
                feedItemInput.body = messageBodyInput;
                // The FeedElementCapabilitiesInput object holds the capabilities of the feed item.
                // For this feed item, we define a direct message capability to hold the member(s) and the subject.
                List<String> memberIds = new List<String>();
                for(String currentId : lstManagersId){
                    memberIds.add(currentId);
                }
                ConnectApi.DirectMessageCapabilityInput dmInput = new ConnectApi.DirectMessageCapabilityInput();
                dmInput.subject = 'Thank you!';
                dmInput.membersToAdd = memberIds;
                ConnectApi.FeedElementCapabilitiesInput feedElementCapabilitiesInput = new ConnectApi.FeedElementCapabilitiesInput();
                feedElementCapabilitiesInput.directMessage = dmInput;
                feedItemInput.capabilities = feedElementCapabilitiesInput;
                // Post the feed item. 
                ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedItemInput); 
                return true;
            }
            return false;
        } catch (Exception e) {
            return false;
        }
    }
}