force-app/main/default/objects/Evaluated_KPI__c/Evaluated_KPI__c.object-meta.xml
<CustomObject>
    <label>Evaluated KPI</label>
    <nameField>
        <label>Evaluated KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluated KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluated_KPI__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI</label>
    <referenceTo>KPI__c</referenceTo>
    <relationshipLabel>Evaluated KPIs</relationshipLabel>
    <relationshipName>Evaluated_KPIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evaluated_KPI__c/fields/Point__c.field-meta.xml
<CustomField>
    <fullName>Point__c</fullName>
    <label>Point</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluated_KPI__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Evaluated KPIs</relationshipLabel>
    <relationshipName>Evaluated_KPIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KPI__c/KPI__c.object-meta.xml
<CustomObject>
    <label>KPI</label>
    <nameField>
        <label>KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LWCEvaluatedKpiControllerTest.cls
@isTest
public class LWCEvaluatedKpiControllerTest {
    @isTest
    public static void testGetEvaluatedKpi(){
        //System Admin
        User admin = TestDataFactory.createAdminUser();
        List<Evaluated_Kpi__c> evaluatedKpiList = new List<Evaluated_Kpi__c>();
		Map<String, List<Evaluated_Kpi__c>> evaluatedKpiListBySection = new Map<String, List<Evaluated_Kpi__c>>();
        
        System.runAs(admin){
            //Account
            Account acc = TestDataFactory.createAccount();
            //Contact
            Contact con = TestDataFactory.createContact(acc.Id);
            //User
            User usr = TestDataFactory.createUser(con.Id);
            //Opportunity
            Opportunity project = TestDataFactory.createOpportunity('Test', acc.Id);
            //Review
            Review__c review = TestDataFactory.createReview(con.Id, project.Id, 'Open');
            //Kpis
            Kpi__c kpi1 = TestDataFactory.createKpis('Apex');
            Kpi__c kpi2 = TestDataFactory.createKpis('LWC');
            //Evaluated Kpi
            Evaluated_Kpi__c ek1 = TestDataFactory.createEvaluatedKpi(review.Id, kpi1.Id, 4);
            Evaluated_Kpi__c ek2 = TestDataFactory.createEvaluatedKpi(review.Id, kpi2.Id, 3);
            
            Test.startTest();
                evaluatedKpiList = LWCEvaluatedKpiController.getEvaluatedKpi(review.Id);
            	evaluatedKpiListBySection = LWCEvaluatedKpiController.getEvaluatedKpiBySection(review.Id);
            Test.stopTest();
            
            System.assertEquals(2, evaluatedKpiList.size(), 'Size of EvaluatedKpi do not match');
            System.assertEquals(1, evaluatedKpiListBySection.size(), 'Size of EvaluatedKpiBySection do not match');

        }
    }

    @isTest
    public static void testSetEvaluatedKpi(){
        //System Admin
        User admin = TestDataFactory.createAdminUser();
        System.runAs(admin) {
            //Account
            Account acc = TestDataFactory.createAccount();
            //Contact
            Contact con = TestDataFactory.createContact(acc.Id);
            //User
            User newUser = TestDataFactory.createUser(con.Id);
            //Opportunity
            Opportunity project = TestDataFactory.createOpportunity('Test', acc.Id);
            //Review
            Review__c review = TestDataFactory.createReview(con.Id, project.Id, 'Open');
            //Kpis
            Kpi__c kpi1 = TestDataFactory.createKpis('Apex');
            Kpi__c kpi2 = TestDataFactory.createKpis('LWC');
            //Evaluated Kpi
            Evaluated_Kpi__c ek1 = TestDataFactory.createEvaluatedKpi(review.Id, kpi1.Id, 2);
            Evaluated_Kpi__c ek2 = TestDataFactory.createEvaluatedKpi(review.Id, kpi2.Id, 1);

            String jsonKpis = '[[{"kpiId": "'+ek1.Id+'","point":"3"}],[{"kpiId": "'+ek2.Id+'","point":"4"}]]';
            
            Test.startTest();
                LWCEvaluatedKpiController.setEvaluatedKpi(jsonKpis);
            Test.stopTest();

            Evaluated_Kpi__c pointUpdate = [ SELECT Point__c FROM Evaluated_Kpi__c WHERE Id = :ek1.Id ];
            System.assertEquals(3, pointUpdate.Point__c);
        }
    }
}