force-app/main/default/objects/Evaluated_KPI__c/Evaluated_KPI__c.object-meta.xml
<CustomObject>
    <label>Evaluated KPI</label>
    <nameField>
        <label>Evaluated KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluated KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluated_KPI__c/fields/KPI__c.field-meta.xml
<CustomField>
    <fullName>KPI__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>KPI</label>
    <referenceTo>KPI__c</referenceTo>
    <relationshipLabel>Evaluated KPIs</relationshipLabel>
    <relationshipName>Evaluated_KPIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Evaluated_KPI__c/fields/Point__c.field-meta.xml
<CustomField>
    <fullName>Point__c</fullName>
    <label>Point</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Evaluated_KPI__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Evaluated KPIs</relationshipLabel>
    <relationshipName>Evaluated_KPIs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/KPI__c/KPI__c.object-meta.xml
<CustomObject>
    <label>KPI</label>
    <nameField>
        <label>KPI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>KPIs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/KPI__c/fields/Section__c.field-meta.xml
<CustomField>
    <fullName>Section__c</fullName>
    <label>Section</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Section 1</fullName>
            </value>
            <value>
                <fullName>Section 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LWCEvaluatedKpiController.cls
public with sharing class LWCEvaluatedKpiController {
   
    @AuraEnabled(cacheable=true)
    public static List<Evaluated_Kpi__c> getEvaluatedKpi(String reviewId){
        
        List<Evaluated_Kpi__c> evaluatedKpiList = [
                SELECT Name, Point__c, KPI__c, Review__r.Status__c, Reason__c, KPI__r.Description__c
                FROM Evaluated_Kpi__c
                WHERE Review__r.Id = :reviewId
                ];
            return evaluatedKpiList;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, List<Evaluated_Kpi__c>> getEvaluatedKpiBySection(String reviewId){
        Map<String, List<Evaluated_Kpi__c>> mapSectionKpi = new Map<String, List<Evaluated_Kpi__c>>(); 
        for (Evaluated_Kpi__c evKpi: [SELECT Name, Point__c, KPI__c, Review__r.Status__c, KPI__r.Section__c, Reason__c, KPI__r.Description__c
                                        FROM Evaluated_Kpi__c
                                        WHERE Review__r.Id = :reviewId]){
                                            if (!mapSectionKpi.containsKey(evKpi.KPI__r.Section__c)){
                                                mapSectionKpi.put(evKpi.KPI__r.Section__c, new List<Evaluated_Kpi__c>());
                                            }
                                            List<Evaluated_Kpi__c> listKPI= mapSectionKpi.get(evKpi.KPI__r.Section__c);
                                            listKPI.add(evKpi);
                                            mapSectionKpi.put(evKpi.KPI__r.Section__c, listKPI);

                }
        return mapSectionKpi;
    }
    
    @AuraEnabled
    public static void setEvaluatedKpi(String evaluatedKpis){
        
        List<Evaluated_Kpi__c> evaluatedKpisToSet = new List<Evaluated_Kpi__c>();
        List<List<EvaluatedKpisWrapper>> evaluatedKpiWrapper = parse(evaluatedKpis);
        
        for( List<EvaluatedKpisWrapper> kpisList: evaluatedKpiWrapper ){
            for( EvaluatedKpisWrapper kpi: kpisList ){
                Evaluated_Kpi__c newEvaluatedKpi = new Evaluated_Kpi__c();
                newEvaluatedKpi.Id = kpi.kpiId;
                newEvaluatedKpi.Point__c = decimal.valueOf(kpi.point);
                newEvaluatedKpi.Reason__c = kpi.reason;
                evaluatedKpisToSet.add(newEvaluatedKpi);
            }
        }
        update evaluatedKpisToSet;
    }

    private class EvaluatedKpisWrapper {
        public String kpiId;
        public String point;
        public String reason;

    }

    public static List<List<EvaluatedKpisWrapper>> parse(String json) {
        return (List<List<EvaluatedKpisWrapper>>) System.JSON.deserialize(json, List<List<EvaluatedKpisWrapper>>.class);
    }
}