force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/Salesforce_Career_Path_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Salesforce Career Path Settings</label>
    <pluralLabel>Salesforce Career Path Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Soft_skills__c.field-meta.xml
<CustomField>
    <fullName>Soft_skills__c</fullName>
    <label>Soft skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LWCEmployeeRoleControllerTest.cls
@isTest
 public class LWCEmployeeRoleControllerTest {   
    
    @isTest
    public static void getRoleInformationTest(){
        User admin = TestDataFactory.createAdminUser();
        Salesforce_Career_Path_Settings__mdt newPathSettings;
        System.runAs(admin){
        	Account acc = TestDataFactory.createAccount();
           	Contact con = TestDataFactory.createContact(acc.Id);
           	con.Role__c = 'Salesforce Trainee';
           	update con;
            User usr = TestDataFactory.createUser(con.Id);
            Test.startTest();
            System.runAs(usr){
                newPathSettings = LWCEmployeeRoleController.getRoleInformation(con.Id);
            }
            Test.stopTest();
            System.assertEquals('Comunicación escrita y oral, con equipo', newPathSettings.Soft_skills__c, 'The softskill do not match');
        }
    } 

    @isTest
    public static void getRoleInformationByNameTest(){
        User admin = TestDataFactory.createAdminUser();
        Salesforce_Career_Path_Settings__mdt newPathSettings;
        System.runAs(admin){
        	Account acc = TestDataFactory.createAccount();
           	Contact con = TestDataFactory.createContact(acc.Id);
           	con.Role__c = 'Salesforce Trainee';
           	update con;
            User usr = TestDataFactory.createUser(con.Id);
            Test.startTest();
            System.runAs(usr){
                newPathSettings = LWCEmployeeRoleController.getRoleInformationByName('Developer');
            }
            Test.stopTest();
            System.assertNotEquals(null, newPathSettings, 'Developer Role is not available in metadata');
        }
    } 
}