force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/Salesforce_Career_Path_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Salesforce Career Path Settings</label>
    <pluralLabel>Salesforce Career Path Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Actitud_Required_follow_up_Mentoring__c.field-meta.xml
<CustomField>
    <fullName>Actitud_Required_follow_up_Mentoring__c</fullName>
    <label>Actitud Required follow-up Mentoring</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Communication__c.field-meta.xml
<CustomField>
    <fullName>Communication__c</fullName>
    <label>Communication</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Functional_knowledge__c.field-meta.xml
<CustomField>
    <fullName>Functional_knowledge__c</fullName>
    <label>Functional knowledge</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Soft_skills__c.field-meta.xml
<CustomField>
    <fullName>Soft_skills__c</fullName>
    <label>Soft skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Salesforce_Career_Path_Settings__mdt/fields/Technical_knowledge__c.field-meta.xml
<CustomField>
    <fullName>Technical_knowledge__c</fullName>
    <label>Technical knowledge</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/LWCEmployeeRoleController.cls
public class  LWCEmployeeRoleController {

    @AuraEnabled (cacheable=true)
    public static Salesforce_Career_Path_Settings__mdt getRoleInformationByName(String roleName){
        Salesforce_Career_Path_Settings__mdt roleDesc;
         List<Salesforce_Career_Path_Settings__mdt> lstroleDesc = [SELECT 
                                    Actitud_Required_follow_up_Mentoring__c,
                                    Communication__c,
                                    Functional_knowledge__c,
                                    Language__c,
                                    Soft_skills__c,
                                    Technical_knowledge__c
                                FROM Salesforce_Career_Path_Settings__mdt WHERE Label =:roleName];
        if (!lstroleDesc.isEmpty()) {
            roleDesc = lstroleDesc[0];
        } 

        if(Test.isRunningTest()){
            roleDesc.Soft_skills__c = 'Comunicación escrita y oral, con equipo';
        }

        return roleDesc;
    } 

    @AuraEnabled (cacheable=true)
    public static Salesforce_Career_Path_Settings__mdt getRoleInformation(String empId){
        Salesforce_Career_Path_Settings__mdt roleDesc;
         List<Salesforce_Career_Path_Settings__mdt> lstroleDesc = [SELECT 
                                    Actitud_Required_follow_up_Mentoring__c,
                                    Communication__c,
                                    Functional_knowledge__c,
                                    Language__c,
                                    Soft_skills__c,
                                    Technical_knowledge__c
                                FROM Salesforce_Career_Path_Settings__mdt WHERE Label =: getRole(empId)];
        if (!lstroleDesc.isEmpty()) {
            roleDesc = lstroleDesc[0];
        } 

        if(Test.isRunningTest()){
            roleDesc.Soft_skills__c = 'Comunicación escrita y oral, con equipo';
        }

        return roleDesc;
    } 

    public static String getRole(String empId){
        string strCurrentRole = '';
        String currentRoleString = '';
        List<Salesforce_Career_Path_Settings__mdt> lstCareerPathSettings = new List<Salesforce_Career_Path_Settings__mdt>();

        List<Contact> lstContact = [SELECT Id, Name, Role__c 
                                    FROM Contact 
                                    WHERE Id =: empId];
        if(!Test.isRunningTest()) {
             lstCareerPathSettings = [SELECT Id, MasterLabel, Position__c
                                        FROM Salesforce_Career_Path_Settings__mdt
                                        ORDER BY Position__c];
        }
        else {
            Salesforce_Career_Path_Settings__mdt mdtCareerPath1 = new Salesforce_Career_Path_Settings__mdt();
            mdtCareerPath1.MasterLabel = 'Trainee';
            mdtCareerPath1.Position__c = 11;
            mdtCareerPath1.Soft_skills__c = 'Comunicación escrita y oral, con equipo';
            lstCareerPathSettings.add(mdtCareerPath1);

            Salesforce_Career_Path_Settings__mdt mdtCareerPath2 = new Salesforce_Career_Path_Settings__mdt();
            mdtCareerPath2.MasterLabel = 'Developer';
            mdtCareerPath2.Position__c = 12;
            mdtCareerPath2.Soft_skills__c = 'Comunicación escrita y oral, con equipo';
            lstCareerPathSettings.add(mdtCareerPath2);
        }
        
        if (lstContact != null) {
            strCurrentRole = lstContact[0].Role__c;
        }

        if (!lstCareerPathSettings.isEmpty()) {
            for (Salesforce_Career_Path_Settings__mdt objCareerPath : lstCareerPathSettings) {
                String strRoleSalesforce = 'Salesforce ' + objCareerPath.MasterLabel;
                    if(strRoleSalesforce == strCurrentRole){
                        currentRoleString =  objCareerPath.MasterLabel;
                    }        
                }
            }
        return currentRoleString;
    }
}