force-app/main/default/objects/Contact/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Base_Category__c.field-meta.xml
<CustomField>
    <fullName>Base_Category__c</fullName>
    <label>Base Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Sub_Project__c</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/Employee_Status__c.object-meta.xml
<CustomObject>
    <label>Employee Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Employee Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Status__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Statuses</relationshipLabel>
    <relationshipName>Employee_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Estado a nivel de la empresa</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/Managers_Assignment__c.object-meta.xml
<CustomObject>
    <label>Managers Assignment</label>
    <nameField>
        <displayFormat>MA-{0000}</displayFormat>
        <label>Managers Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Managers Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Managers_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Sub_Project__c</referenceTo>
    <relationshipLabel>Managers Assignments</relationshipLabel>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Managers_Assignment__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Managers_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sub_Project__c/Sub_Project__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sub_Project__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Sub Projects</relationshipLabel>
    <relationshipName>Sub_Projects</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmployeeController.cls
public class EmployeeController {

    @AuraEnabled
    public static List<EmployeeWrapper> getEmployeeWithLastStatus() {
        List<EmployeeWrapper> wrapper = resolveUserEmployees();
        
        return wrapper;
    }
    
    public class EmployeeWrapper {
        @AuraEnabled public String id { get; set; }
        @AuraEnabled public String employeeId { get; set; }
        @AuraEnabled public String employee { get; set; }
        @AuraEnabled public String status { get; set; }
        @AuraEnabled public DateTime lastdate { get; set; }
    }
    
    private static List<EmployeeWrapper> resolveUserEmployees() {
        List<Managers_Assignment__c> userAssignments = getUserAssignments();
        Set<Id> userProjects = new Set<Id>();
        
        for (Managers_Assignment__c assignment : userAssignments) {
            userProjects.add(assignment.Project__c);
        }
        
        List<Employee_Assignment__c> employeeAssignments = getEmployeeAssignmentsByProjectId( userProjects );
        Set<Id> userEmployees = getEmployeesFromAssignments(employeeAssignments);
        
        Map<Id, Contact> userEmployeesById = new Map<Id, Contact>(
            getEmployeesById(userEmployees)
        );
        
        List<Employee_Status__c> employeeStatus = getEmployeeStatusByEmployeeId(userEmployees);
        Map<Id, Employee_Status__c> lastEmployeeStatusByEmployee = resolveLastEmployeeStatus(employeeStatus);
        
        return resolveEmployeeWrapper(userEmployeesById, lastEmployeeStatusByEmployee);
    }
    
    private static List<Managers_Assignment__c> getUserAssignments() {
        return [SELECT Id, Project__c, Sub_Project__c FROM Managers_Assignment__c WHERE User__c = :UserInfo.getUserId()];
    }
    
    private static List<Employee_Assignment__c> getEmployeeAssignmentsByProjectId( Set<Id> projectIds ) {
        
        List<Employee_Assignment__c> toReturn = new List<Employee_Assignment__c>();
        
        for (Employee_Assignment__c ea: [SELECT Id, Employee__c, Project__c,  Sub_Project__c 
                                         FROM Employee_Assignment__c 
                                         WHERE Project__c IN :projectIds 
                                         AND Employee__r.Active__c = true 
                                         AND End_Date__c >: date.today() 
                                         AND Base_Category__c!='']){
            toReturn.add(ea);
        }
        return toReturn;
    }
    
    private static List<Employee_Status__c> getEmployeeStatusByEmployeeId(Set<Id> employeeIds) {
        return [
            SELECT
               Id,
               Employee__c,
               Employee__r.Name,
               Status__c,
               LastModifiedDate
            FROM Employee_Status__c
            WHERE Employee__c IN :employeeIds
            ORDER BY LastModifiedDate DESC
        ];
    }
    
    private static Set<Id> getEmployeesFromAssignments(List<Employee_Assignment__c> employeeAssignments) {
        Set<Id> employees = new Set<Id>();
        
        for (Employee_Assignment__c assignment : employeeAssignments) {
            employees.add(assignment.Employee__c);
        }
        
        return employees;
    }
    
    private static Map<Id, Employee_Status__c> resolveLastEmployeeStatus(List<Employee_Status__c> employeeStatus) {
        Map<Id, Employee_Status__c> lastEmployeeStatusByEmployee = new Map<Id, Employee_Status__c>();
        
        for (Employee_Status__c eStatus : employeeStatus) {
            if (!lastEmployeeStatusByEmployee.containsKey(eStatus.Employee__c)) {
                lastEmployeeStatusByEmployee.put(eStatus.Employee__c, eStatus);
            }
        }
        
        return lastEmployeeStatusByEmployee;
    }
    
    private static List<Contact> getEmployeesById(Set<Id> employeeIds) {
        return [SELECT Id, Name FROM Contact WHERE Id IN :employeeIds and Area__c = 'Salesforce'];
    }
    
    private static List<EmployeeWrapper> resolveEmployeeWrapper(
        Map<Id, Contact> userEmployeesById,
        Map<Id, Employee_Status__c> lastEmployeeStatusByEmployee
    ) {
        List<EmployeeWrapper> wrapper = new List<EmployeeWrapper>();
        Map<Id, String> lastStatusByEmployee = new Map<Id, String>();
        
        for (Id employee : userEmployeesById.keySet()) {
            if (lastEmployeeStatusByEmployee.containsKey(employee)) {
                EmployeeWrapper newWrapper = getEmployeeWrapper(
                    lastEmployeeStatusByEmployee.get(employee)
                );

                wrapper.add(newWrapper);
            } else {
                Contact currentEmployee = userEmployeesById.get(employee);
                EmployeeWrapper newWrapper = getEmployeeWrapper(currentEmployee);

                wrapper.add(newWrapper);
            }
        }

        return wrapper;
    }
    
    private static EmployeeWrapper getEmployeeWrapper(Employee_Status__c employeeStatus) {
        EmployeeWrapper newWrapper = new EmployeeWrapper();
        newWrapper.id = employeeStatus.Id;
        newWrapper.employeeId = employeeStatus.Employee__c;
        newWrapper.employee = employeeStatus.Employee__r.Name;
        newWrapper.status = employeeStatus.Status__c;
        newWrapper.lastdate = employeeStatus.LastModifiedDate;
                    
        return newWrapper;
    }
    
    private static EmployeeWrapper getEmployeeWrapper(Contact employee) {
        EmployeeWrapper newWrapper = new EmployeeWrapper();
        newWrapper.id = '';
        newWrapper.employeeId = employee.Id;
        newWrapper.employee = employee.Name;
        newWrapper.status = '';
                    
        return newWrapper;
    }
}