force-app/main/default/objects/Contact/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/Employee_Assignment__c.object-meta.xml
<CustomObject>
    <label>Employee Assignment</label>
    <nameField>
        <displayFormat>EA-{0000}</displayFormat>
        <label>Employee Assignments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Assignment__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Assignment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Employee Assignments</relationshipLabel>
    <relationshipName>Employee_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Area</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Area.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce</fullName>
        <default>true</default>
        <label>Salesforce</label>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Area</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EmployeeAssignmentsTriggerTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────┐
* Employee Assignments Trigger Tests
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Schubert Tonarelli   <stonarelli@altimetrik.com>
* @created        2020-04-20
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @changes
* ─────────────────────────────────────────────────────────────────────────────────────────────────┘
*/
@isTest
public class EmployeeAssignmentsTriggerTest {
    
    @testSetup 
    static void setupTest(){

        Account testAccount = new Account( Name = 'TestAccount' );
        insert testAccount;
        
        Contact testContact = new Contact(
        	FirstName = 'Schubert',
            LastName = 'Tonarelli',
            Email = 'st@test.com',
        	AccountId = testAccount.Id
        );
        insert testContact;
        
        Opportunity testOpty = new Opportunity(
        	AccountId = testAccount.Id,
            CloseDate = Date.today().addYears(2),
            Area__c = 'Salesforce',
            StageName = 'Accepted',
            Name = 'Test1'
        );
        insert testOpty;
        
        Employee_Assignment__c testEmpAss = new Employee_Assignment__c(
        	Employee__c = testContact.Id,
            Project__c = testOpty.Id,
            Start_Date__c = Date.today().addDays(-1),
            End_Date__c = Date.today()
        );
        insert testEmpAss;
    }
	
    @isTest
    static void projectStartEndDate() {
        Opportunity testOpty =  [SELECT StageName FROM Opportunity WHERE Name = 'Test1' LIMIT 1];
        system.assert( testOpty.StageName == 'In Progress' );
    }
}