force-app/main/default/objects/Plan_Item__c/Plan_Item__c.object-meta.xml
<CustomObject>
    <label>Plan Item</label>
    <nameField>
        <label>Plan Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Item__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Plan Items</relationshipLabel>
    <relationshipName>Plan_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LWCReviewPlanItemsControllerTest.cls
@isTest
public class LWCReviewPlanItemsControllerTest {

    @isTest
    public static void getPlanItemsTest(){
        User admin = TestDataFactory.createAdminUser();
        List<Plan_Item__c> planItemList = new List<Plan_Item__c>();
        System.runAs(admin){
        	Account acc = TestDataFactory.createAccount();
           	Contact con = TestDataFactory.createContact(acc.Id);
            User usr = TestDataFactory.createUser(con.Id);
            Opportunity project = TestDataFactory.createOpportunity('Test', acc.Id);
            Review__c review = TestDataFactory.createReview(con.Id, project.Id, 'Open');
            Review__c review2 = TestDataFactory.createReview(con.Id, project.Id, 'Open');
            Plan_Item__c pi1 = TestDataFactory.createPlanItem(review.Id, 'Started', Date.Today());
            Plan_Item__c pi2 = TestDataFactory.createPlanItem(review.Id, 'Started', Date.Today());
            Plan_Item__c pi3 = TestDataFactory.createPlanItem(review.Id, 'Started', Date.Today());
            Plan_Item__c pi4 = TestDataFactory.createPlanItem(review2.Id, 'Started', Date.Today());
            Test.startTest();
            planItemList = LWCReviewPlanItemsController.getPlanItems(review.Id);
            Test.stopTest();
            System.assertEquals(3, planItemList.size(), 'Returned plan items do not match');
        }
    } 
}