force-app/main/default/objects/Plan_Item__c/Plan_Item__c.object-meta.xml
<CustomObject>
    <label>Plan Item</label>
    <nameField>
        <label>Plan Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plan Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan_Item__c/fields/Plan__c.field-meta.xml
<CustomField> 
    <fullName>Plan__c</fullName> 
    <label>Plan</label> 
    <length>131072</length> 
    <type>LongTextArea</type> 
</CustomField>

force-app/main/default/objects/Plan_Item__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Review</label>
    <referenceTo>Review__c</referenceTo>
    <relationshipLabel>Plan Items</relationshipLabel>
    <relationshipName>Plan_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan_Item__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Non Started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Review__c/Review__c.object-meta.xml
<CustomObject>
    <label>Review</label>
    <nameField>
        <displayFormat>Review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LWCReviewPlanItemsController.cls
public class LWCReviewPlanItemsController {
    @AuraEnabled(cacheable=true)
    public static List<Plan_Item__c> getPlanItems(String reviewId){
        List<Plan_Item__c> planItemList = [SELECT Name, State__c, End_Date__c, Plan__c
                                                FROM Plan_Item__c
                                            WHERE Review__r.Id = :reviewId];
            return planItemList;
    }
}