force-app/main/default/objects/Employee_Status__c/Employee_Status__c.object-meta.xml
<CustomObject>
    <label>Employee Status</label>
    <nameField>
        <displayFormat>ES-{0000}</displayFormat>
        <label>Employee Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employee Statuses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee_Status__c/fields/Certification_Status__c.field-meta.xml
<CustomField>
    <fullName>Certification_Status__c</fullName>
    <inlineHelpText>Green = acorde al role o superior, Yellow = preparando, Red= no interesado</inlineHelpText>
    <label>Certification Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <label>Employee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Employee Statuses</relationshipLabel>
    <relationshipName>Employee_Statuses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Employee_Status__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Estado a nivel de la empresa</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Green</fullName>
                <default>true</default>
                <label>Green</label>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NoEmployeeStatusUpdateNotificationTest.cls
@isTest
public class NoEmployeeStatusUpdateNotificationTest {
    @TestSetup
    static void makeData(){
        Account customer = new Account();
        customer.Name  = 'Test Customer';
        customer.Phone = '44554545545';
        insert customer;
        Contact c1 = new Contact();
        c1.FirstName = 'Test';
        c1.Email= 'test@test.com';
        c1.LastName='morales';
        c1.Role__c='Salesforce Developer';
        insert c1;
        Test.setCreatedDate(c1.Id, Datetime.now().addDays(-60));
        
        Employee_Status__c es =  new Employee_Status__c();
        es.Status__c='Yellow';
        es.Certification_Status__c='Red';
        es.Employee__c = c1.Id;
        insert es;
        Test.setCreatedDate(es.Id, Datetime.now().addDays(-60));
        
    }
    @isTest static void testNoEmployeeStatusUpdateNotification() {
        Test.startTest();

        String jobId = System.schedule('testBasicScheduledApex', '0 0 0 3 9 ? 2022', new NoEmployeeStatusUpdateNotification());
        Test.stopTest();

        List<EmailMessage>  emailMessage  = [SELECT Id FROM EmailMessage LIMIT 1];
        System.assertEquals(1, emailMessage.size());
    }
}